// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) 
    {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web =
   FirebaseOptions(
    apiKey: 'AIzaSyBUG74dv1TGb4s0nL1AY-rn0eV49GMpRlY',
    appId: '1:119515660939:web:2679b74fef2fc5bf170a8e',
    messagingSenderId: '119515660939',
    projectId: 'voice-assistant-853df',
    authDomain: 'voice-assistant-853df.firebaseapp.com',
    storageBucket: 'voice-assistant-853df.appspot.com',
  );


  static const FirebaseOptions android =
   FirebaseOptions(
    apiKey: 'AIzaSyDt1fHG1-VF_iIojRInVkMn2tzpsiunjN4',
    appId: '1:119515660939:android:ce957e0732b40efa170a8e',
    messagingSenderId: '119515660939',
    projectId: 'voice-assistant-853df',
    storageBucket: 'voice-assistant-853df.appspot.com',
  );


  static const FirebaseOptions ios =
   FirebaseOptions(
    apiKey: 'AIzaSyDPexNBI4dDPgyEwyCuSZ3_6id3ziIrzSE',
    appId: '1:119515660939:ios:4f5f35e509c10b4a170a8e',
    messagingSenderId: '119515660939',
    projectId: 'voice-assistant-853df',
    storageBucket: 'voice-assistant-853df.appspot.com',
    iosClientId: '119515660939-850hcnmoblh49263jekh6e9rnsrnsc51.apps.googleusercontent.com',
    iosBundleId: 'com.example.gptFlutter',
  );


  static const FirebaseOptions macos =
   FirebaseOptions(
    apiKey: 'AIzaSyDPexNBI4dDPgyEwyCuSZ3_6id3ziIrzSE',
    appId: '1:119515660939:ios:4f5f35e509c10b4a170a8e',
    messagingSenderId: '119515660939',
    projectId: 'voice-assistant-853df',
    storageBucket: 'voice-assistant-853df.appspot.com',
    iosClientId: '119515660939-850hcnmoblh49263jekh6e9rnsrnsc51.apps.googleusercontent.com',
    iosBundleId: 'com.example.gptFlutter',
  );
}
